name: BigDoors
main: nl.pim16aap2.bigDoors.BigDoors
version: 0.0.1
author: Pim
depend:
 - WorldEdit
commands:
  shutup:
    description: Shuts up debug messages.
    usage: /shutup <debug level>
  pausedoors:
    description: Pauses all door movement until used again.
    usage: /pausedoors
  stopdoors:
    description: Stops all doors.
  newdoor:
    description: Create a new door from selection with name "doorName".
    usage: /newdoor <doorName>
    permission: bigdoors.createdoor
    permission-message: You do not have the bigdoors.createdoor permission node.
  deldoor:
    description: Delete door with name "doorName".
    usage: /deldoor <doorName>
    permission: bigdoors.deletedoor
    permission-message: You do not have the bigdoors.deletedoor permission node.
  opendoor:
    description: Open the door with name "doorName".
    usage: /opendoor <doorName> [speed]
    permission: bigdoors.opendoor
    permission-message: You do not have the bigdoors.opendoor permission node.
  opendoors:
    description: Open the doors with name "doorName1" and "doorName2".
    usage: /opendoors <doorName1> <doorName2> [speed]
    permission: bigdoors.opendoors
    permission-message: You do not have the bigdoors.opendoor permission node.
  listdoors:
    description: Returns a list of all doors.
    usage: /listdoors
    permission: bigdoors.listdoors
    permission-message: You do not have the bigdoors.listdoors permission node.
  fixdoor:
    description: Verify and fix (if needed) the coords of the specifief door.
    useage: /fixdoor <doorName>
    permission: bigdoors.admin.debug
    permission-message: You do not have the bigdoors.listdoors permission node.
  updatedoor:
    description: Update the coords of the specified door.
    usage: /fixdoor <doorName>
    permission: bigdoors.admin.updatedoor
    permissions-message: You do not have the bigdoors.listdoors permission node.
  unlockDoor:
    description: Forcefully unlock a door.
    usage: /unlockdoor <doorName>
    permission: bigdoors.admin.unlockdoor
    